# Generated by Django 3.1.1 on 2020-09-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='id_published',
            new_name='is_published',
        ),
    ]
